FROM python:3.10-slim-bullseye

ENV PYTHONUNBUFFERED 1

RUN mkdir /opt/code
RUN mkdir /opt/requirements
WORKDIR /opt/code

ADD requirements /opt/requirements
RUN apt update && apt install build-essential python3-dev libpq-dev libffi-dev cron -y
RUN pip install -r /opt/requirements/production.txt