version: "3.9"

services:
    web:
        build:
            context: ${PWD}
            dockerfile: Docker/Dockerfile.web.production
        environment:
            FLASK_ENV: ${FLASK_ENV}
            FLASK_CONFIG: ${FLASK_CONFIG}
            SECRET_KEY: ${SECRET_KEY}
            APPLICATION_DB: ${APPLICATION_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PW: ${POSTGRES_PW}
            POSTGRES_PORT: ${POSTGRES_PORT}
        # deploy:
        #   resources:
        #     limits:
        #       cpus: "0"
        #       memory: 384M
        # env_file: ../.env.production
        command: gunicorn -k eventlet -w 3 -b 0.0.0.0 --worker-tmp-dir /dev/shm wsgi:app
        ports:
            - "8000:8000"

    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 8080:8080
        depends_on:
            - web
